/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodePanel: typeof import('./components/panels/CodePanel.vue')['default']
    ProtoCanvas: typeof import('./components/canvas/ProtoCanvas.vue')['default']
    ProtoEdge: typeof import('./components/canvas/ProtoEdge.vue')['default']
    ProtoNode: typeof import('./components/canvas/ProtoNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepPanel: typeof import('./components/panels/StepPanel.vue')['default']
  }
}
